### ISSUE TITLE
Lilly CLI Error when trying to start the development server using Git Bash

### ISSUE THREAD

**Issue by mariushilleke** [TeamArmadilloOrg/teamWebsite#28]
1. opening Git Bash in Windows Terminal
2. choosing the development server option for the website (cf. picture)
![image](https://user-images.githubusercontent.com/29111781/89931038-f2886f00-dc0b-11ea-9cdf-75b38263f89d.png)

3. produces following error

```
$ lilly
 Lilly �:  Hello Marius �, good to see you again!
 Lilly �:  How I can assist you?
 Marius �:  Start the development server for the website project with webpack

 � NOTE:
│ If you would like to do this task without the help of Lilly,
│ simply use this command:
│  pnpm start:website
└
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn pnpm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn pnpm',
  path: 'pnpm',
  spawnargs: [ 'start:website', '' ]
}
```

**Comment by xeho91** [comment]
I managed to reproduce your issue in the same environment.
I found the problem, and I will provide a bugfix in the next version of Lilly. 👍 

I haven't managed to figure out why you have an issue on WSL Ubuntu. I need more info.

**Comment by xeho91** [comment]
Closing this issue, as I have moved the project to separate repository.
